const poemsMetadata = [
  {"filename":"Poems_XML/01-hoc.xml","title":"The Compleynte of the Virgin before the Cross","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/02-hoc.xml","title":"Address to Sir John Oldcastle","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/03-hoc.xml","title":"La Male Regle","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/04-hoc.xml","title":"Balade to King Henry V","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/05-hoc.xml","title":"Two Balades to Henry V and the Knights of the Garter [Ballad #1]","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/06-hoc.xml","title":"Two Balades to Henry V and the Knights of the Garter [Ballad #2]","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/07-hoc.xml","title":"Ad Beatam Virginem","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/08-hoc.xml","title":"Balade, after K. Richard II's Bones . . .","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/09-hoc.xml","title":"Balade to my gracious Lord of York","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/10-hoc.xml","title":"Ad Beatam Vriginem, the 'Mother of God'","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/11-hoc.xml","title":"Balade to the Duke of Bedford","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/12-hoc.xml","title":"Balade to my Lord the Chancellor","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/13-hoc.xml","title":"Balade and Roundel or Chanceon to Mr. Henry Somer, Subtreasurer","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/14-hoc.xml","title":"Balade to King Henry V","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/15-hoc.xml","title":"Balade to King Henry V, for Money","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/16-hoc.xml","title":"Balade to my maister Carpenter","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/17-hoc.xml","title":"Balade by the Court of Good Company","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/18-hoc.xml","title":"Balade to the Virgin and Christ","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/19-hoc.xml","title":"The Letter of Cupid to Lovers, his Subjects","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/21-hoc.xml","title":"Verba compilatoris ad librum [envoi at end of regiment]","title_type":"HUNTINGTON HM 111"},
  {"filename":"Poems_XML/22-hoc.xml","title":"Inoucacio ad patrem","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/23-hoc.xml","title":"ad filium honor et gloria","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/24-hoc.xml","title":"ad spiritum sanctum","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/25-hoc.xml","title":"Ad Beatam Virginem","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/26-hoc.xml","title":"item de beata virgine (prologus)","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/27-hoc.xml","title":"item de beata virgine (fabula)","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/28-hoc.xml","title":"the story of the monk who clad the virgin","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/29-hoc.xml","title":"Three Roundels - Hoccleve's appeal to Lady Money","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/30-hoc.xml","title":"Three Roundels - Lady Money's scornful answer","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/31-hoc.xml","title":"Three Roundels - Hoccleve's Humorous praise of his lady","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/32-hoc.xml","title":"epilogue to three roundels","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/33-hoc.xml","title":"Lerne to Dye.","title_type":"HUNTINGTON HM 744"},
  {"filename":"Poems_XML/34-hoc.xml","title":"Thomas Hoccleve's Complaint","title_type":"Unknown"},
  {"filename":"Poems_XML/35-hoc.xml","title":"Dialog with a Friend","title_type":"DURHAM COSIN V.iii.9"},
  {"filename":"Poems_XML/37-hoc.xml","title":"Lerne to Dye.","title_type":"DURHAM COSIN V.iii.9"},
  {"filename":"Poems_XML/39-hoc.xml","title":"Hoccleve's Dedication to Lady Westmoreland","title_type":"DURHAM COSIN V.iii.9"}
];
